/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as IndexRouteImport } from './routes/index';
import { Route as AuthenticatedRouteImport } from './routes/_authenticated';
import { Route as LoginRouteImport } from './routes/login';
import { Route as AuthenticatedAttendanceRouteImport } from './routes/_authenticated.attendance';
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard';
import { Route as AuthenticatedExpensesRouteImport } from './routes/_authenticated.expenses';
import { Route as AuthenticatedOperatorsRouteImport } from './routes/_authenticated.operators';
import { Route as AuthenticatedPaymentsRouteImport } from './routes/_authenticated.payments';
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated.profile';
import { Route as AuthenticatedScheduleRouteImport } from './routes/_authenticated.schedule';
import { Route as AuthenticatedTeachersRouteImport } from './routes/_authenticated.teachers';
import { Route as AuthenticatedAuditIndexRouteImport } from './routes/_authenticated.audit.index';
import { Route as AuthenticatedAuditIdRouteImport } from './routes/_authenticated.audit.$id';
import { Route as AuthenticatedBranchesIndexRouteImport } from './routes/_authenticated.branches.index';
import { Route as AuthenticatedBranchesIdRouteImport } from './routes/_authenticated.branches.$id';
import { Route as AuthenticatedCoursesIndexRouteImport } from './routes/_authenticated.courses.index';
import { Route as AuthenticatedCoursesIdRouteImport } from './routes/_authenticated.courses.$id';
import { Route as AuthenticatedExpensesIdRouteImport } from './routes/_authenticated.expenses.$id';
import { Route as AuthenticatedGroupsIndexRouteImport } from './routes/_authenticated.groups.index';
import { Route as AuthenticatedGroupsIdRouteImport } from './routes/_authenticated.groups.$id';
import { Route as AuthenticatedStudentsIndexRouteImport } from './routes/_authenticated.students.index';
import { Route as AuthenticatedStudentsIdRouteImport } from './routes/_authenticated.students.$id';
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated.users.index';
import { Route as AuthenticatedUsersIdRouteImport } from './routes/_authenticated.users.$id';

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any);
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any);
const AuthenticatedAttendanceRoute = AuthenticatedAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AuthenticatedRoute,
} as any);
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any);
const AuthenticatedExpensesRoute = AuthenticatedExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AuthenticatedRoute,
} as any);
const AuthenticatedOperatorsRoute = AuthenticatedOperatorsRouteImport.update({
  id: '/operators',
  path: '/operators',
  getParentRoute: () => AuthenticatedRoute,
} as any);
const AuthenticatedPaymentsRoute = AuthenticatedPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AuthenticatedRoute,
} as any);
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any);
const AuthenticatedScheduleRoute = AuthenticatedScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AuthenticatedRoute,
} as any);
const AuthenticatedTeachersRoute = AuthenticatedTeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => AuthenticatedRoute,
} as any);
const AuthenticatedAuditIndexRoute = AuthenticatedAuditIndexRouteImport.update({
  id: '/audit/',
  path: '/audit/',
  getParentRoute: () => AuthenticatedRoute,
} as any);
const AuthenticatedAuditIdRoute = AuthenticatedAuditIdRouteImport.update({
  id: '/audit/$id',
  path: '/audit/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any);
const AuthenticatedBranchesIndexRoute =
  AuthenticatedBranchesIndexRouteImport.update({
    id: '/branches/',
    path: '/branches/',
    getParentRoute: () => AuthenticatedRoute,
  } as any);
const AuthenticatedBranchesIdRoute = AuthenticatedBranchesIdRouteImport.update({
  id: '/branches/$id',
  path: '/branches/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any);
const AuthenticatedCoursesIndexRoute =
  AuthenticatedCoursesIndexRouteImport.update({
    id: '/courses/',
    path: '/courses/',
    getParentRoute: () => AuthenticatedRoute,
  } as any);
const AuthenticatedCoursesIdRoute = AuthenticatedCoursesIdRouteImport.update({
  id: '/courses/$id',
  path: '/courses/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any);
const AuthenticatedExpensesIdRoute = AuthenticatedExpensesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedExpensesRoute,
} as any);
const AuthenticatedGroupsIndexRoute =
  AuthenticatedGroupsIndexRouteImport.update({
    id: '/groups/',
    path: '/groups/',
    getParentRoute: () => AuthenticatedRoute,
  } as any);
const AuthenticatedGroupsIdRoute = AuthenticatedGroupsIdRouteImport.update({
  id: '/groups/$id',
  path: '/groups/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any);
const AuthenticatedStudentsIndexRoute =
  AuthenticatedStudentsIndexRouteImport.update({
    id: '/students/',
    path: '/students/',
    getParentRoute: () => AuthenticatedRoute,
  } as any);
const AuthenticatedStudentsIdRoute = AuthenticatedStudentsIdRouteImport.update({
  id: '/students/$id',
  path: '/students/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any);
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRoute,
} as any);
const AuthenticatedUsersIdRoute = AuthenticatedUsersIdRouteImport.update({
  id: '/users/$id',
  path: '/users/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/login': typeof LoginRoute;
  '/attendance': typeof AuthenticatedAttendanceRoute;
  '/dashboard': typeof AuthenticatedDashboardRoute;
  '/expenses': typeof AuthenticatedExpensesRouteWithChildren;
  '/operators': typeof AuthenticatedOperatorsRoute;
  '/payments': typeof AuthenticatedPaymentsRoute;
  '/profile': typeof AuthenticatedProfileRoute;
  '/schedule': typeof AuthenticatedScheduleRoute;
  '/teachers': typeof AuthenticatedTeachersRoute;
  '/audit/$id': typeof AuthenticatedAuditIdRoute;
  '/branches/$id': typeof AuthenticatedBranchesIdRoute;
  '/courses/$id': typeof AuthenticatedCoursesIdRoute;
  '/expenses/$id': typeof AuthenticatedExpensesIdRoute;
  '/groups/$id': typeof AuthenticatedGroupsIdRoute;
  '/students/$id': typeof AuthenticatedStudentsIdRoute;
  '/users/$id': typeof AuthenticatedUsersIdRoute;
  '/audit/': typeof AuthenticatedAuditIndexRoute;
  '/branches/': typeof AuthenticatedBranchesIndexRoute;
  '/courses/': typeof AuthenticatedCoursesIndexRoute;
  '/groups/': typeof AuthenticatedGroupsIndexRoute;
  '/students/': typeof AuthenticatedStudentsIndexRoute;
  '/users/': typeof AuthenticatedUsersIndexRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/login': typeof LoginRoute;
  '/attendance': typeof AuthenticatedAttendanceRoute;
  '/dashboard': typeof AuthenticatedDashboardRoute;
  '/expenses': typeof AuthenticatedExpensesRouteWithChildren;
  '/operators': typeof AuthenticatedOperatorsRoute;
  '/payments': typeof AuthenticatedPaymentsRoute;
  '/profile': typeof AuthenticatedProfileRoute;
  '/schedule': typeof AuthenticatedScheduleRoute;
  '/teachers': typeof AuthenticatedTeachersRoute;
  '/audit/$id': typeof AuthenticatedAuditIdRoute;
  '/branches/$id': typeof AuthenticatedBranchesIdRoute;
  '/courses/$id': typeof AuthenticatedCoursesIdRoute;
  '/expenses/$id': typeof AuthenticatedExpensesIdRoute;
  '/groups/$id': typeof AuthenticatedGroupsIdRoute;
  '/students/$id': typeof AuthenticatedStudentsIdRoute;
  '/users/$id': typeof AuthenticatedUsersIdRoute;
  '/audit': typeof AuthenticatedAuditIndexRoute;
  '/branches': typeof AuthenticatedBranchesIndexRoute;
  '/courses': typeof AuthenticatedCoursesIndexRoute;
  '/groups': typeof AuthenticatedGroupsIndexRoute;
  '/students': typeof AuthenticatedStudentsIndexRoute;
  '/users': typeof AuthenticatedUsersIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/_authenticated': typeof AuthenticatedRouteWithChildren;
  '/login': typeof LoginRoute;
  '/_authenticated/attendance': typeof AuthenticatedAttendanceRoute;
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute;
  '/_authenticated/expenses': typeof AuthenticatedExpensesRouteWithChildren;
  '/_authenticated/operators': typeof AuthenticatedOperatorsRoute;
  '/_authenticated/payments': typeof AuthenticatedPaymentsRoute;
  '/_authenticated/profile': typeof AuthenticatedProfileRoute;
  '/_authenticated/schedule': typeof AuthenticatedScheduleRoute;
  '/_authenticated/teachers': typeof AuthenticatedTeachersRoute;
  '/_authenticated/audit/$id': typeof AuthenticatedAuditIdRoute;
  '/_authenticated/branches/$id': typeof AuthenticatedBranchesIdRoute;
  '/_authenticated/courses/$id': typeof AuthenticatedCoursesIdRoute;
  '/_authenticated/expenses/$id': typeof AuthenticatedExpensesIdRoute;
  '/_authenticated/groups/$id': typeof AuthenticatedGroupsIdRoute;
  '/_authenticated/students/$id': typeof AuthenticatedStudentsIdRoute;
  '/_authenticated/users/$id': typeof AuthenticatedUsersIdRoute;
  '/_authenticated/audit/': typeof AuthenticatedAuditIndexRoute;
  '/_authenticated/branches/': typeof AuthenticatedBranchesIndexRoute;
  '/_authenticated/courses/': typeof AuthenticatedCoursesIndexRoute;
  '/_authenticated/groups/': typeof AuthenticatedGroupsIndexRoute;
  '/_authenticated/students/': typeof AuthenticatedStudentsIndexRoute;
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/login'
    | '/attendance'
    | '/dashboard'
    | '/expenses'
    | '/operators'
    | '/payments'
    | '/profile'
    | '/schedule'
    | '/teachers'
    | '/audit/$id'
    | '/branches/$id'
    | '/courses/$id'
    | '/expenses/$id'
    | '/groups/$id'
    | '/students/$id'
    | '/users/$id'
    | '/audit/'
    | '/branches/'
    | '/courses/'
    | '/groups/'
    | '/students/'
    | '/users/';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/'
    | '/login'
    | '/attendance'
    | '/dashboard'
    | '/expenses'
    | '/operators'
    | '/payments'
    | '/profile'
    | '/schedule'
    | '/teachers'
    | '/audit/$id'
    | '/branches/$id'
    | '/courses/$id'
    | '/expenses/$id'
    | '/groups/$id'
    | '/students/$id'
    | '/users/$id'
    | '/audit'
    | '/branches'
    | '/courses'
    | '/groups'
    | '/students'
    | '/users';
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/attendance'
    | '/_authenticated/dashboard'
    | '/_authenticated/expenses'
    | '/_authenticated/operators'
    | '/_authenticated/payments'
    | '/_authenticated/profile'
    | '/_authenticated/schedule'
    | '/_authenticated/teachers'
    | '/_authenticated/audit/$id'
    | '/_authenticated/branches/$id'
    | '/_authenticated/courses/$id'
    | '/_authenticated/expenses/$id'
    | '/_authenticated/groups/$id'
    | '/_authenticated/students/$id'
    | '/_authenticated/users/$id'
    | '/_authenticated/audit/'
    | '/_authenticated/branches/'
    | '/_authenticated/courses/'
    | '/_authenticated/groups/'
    | '/_authenticated/students/'
    | '/_authenticated/users/';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren;
  LoginRoute: typeof LoginRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_authenticated': {
      id: '/_authenticated';
      path: '';
      fullPath: '/';
      preLoaderRoute: typeof AuthenticatedRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/login': {
      id: '/login';
      path: '/login';
      fullPath: '/login';
      preLoaderRoute: typeof LoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_authenticated/attendance': {
      id: '/_authenticated/attendance';
      path: '/attendance';
      fullPath: '/attendance';
      preLoaderRoute: typeof AuthenticatedAttendanceRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard';
      path: '/dashboard';
      fullPath: '/dashboard';
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    '/_authenticated/expenses': {
      id: '/_authenticated/expenses';
      path: '/expenses';
      fullPath: '/expenses';
      preLoaderRoute: typeof AuthenticatedExpensesRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    '/_authenticated/operators': {
      id: '/_authenticated/operators';
      path: '/operators';
      fullPath: '/operators';
      preLoaderRoute: typeof AuthenticatedOperatorsRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    '/_authenticated/payments': {
      id: '/_authenticated/payments';
      path: '/payments';
      fullPath: '/payments';
      preLoaderRoute: typeof AuthenticatedPaymentsRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    '/_authenticated/profile': {
      id: '/_authenticated/profile';
      path: '/profile';
      fullPath: '/profile';
      preLoaderRoute: typeof AuthenticatedProfileRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    '/_authenticated/schedule': {
      id: '/_authenticated/schedule';
      path: '/schedule';
      fullPath: '/schedule';
      preLoaderRoute: typeof AuthenticatedScheduleRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    '/_authenticated/teachers': {
      id: '/_authenticated/teachers';
      path: '/teachers';
      fullPath: '/teachers';
      preLoaderRoute: typeof AuthenticatedTeachersRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    '/_authenticated/audit/': {
      id: '/_authenticated/audit/';
      path: '/audit';
      fullPath: '/audit/';
      preLoaderRoute: typeof AuthenticatedAuditIndexRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    '/_authenticated/audit/$id': {
      id: '/_authenticated/audit/$id';
      path: '/audit/$id';
      fullPath: '/audit/$id';
      preLoaderRoute: typeof AuthenticatedAuditIdRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    '/_authenticated/branches/': {
      id: '/_authenticated/branches/';
      path: '/branches';
      fullPath: '/branches/';
      preLoaderRoute: typeof AuthenticatedBranchesIndexRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    '/_authenticated/branches/$id': {
      id: '/_authenticated/branches/$id';
      path: '/branches/$id';
      fullPath: '/branches/$id';
      preLoaderRoute: typeof AuthenticatedBranchesIdRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    '/_authenticated/courses/': {
      id: '/_authenticated/courses/';
      path: '/courses';
      fullPath: '/courses/';
      preLoaderRoute: typeof AuthenticatedCoursesIndexRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    '/_authenticated/courses/$id': {
      id: '/_authenticated/courses/$id';
      path: '/courses/$id';
      fullPath: '/courses/$id';
      preLoaderRoute: typeof AuthenticatedCoursesIdRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    '/_authenticated/expenses/$id': {
      id: '/_authenticated/expenses/$id';
      path: '/$id';
      fullPath: '/expenses/$id';
      preLoaderRoute: typeof AuthenticatedExpensesIdRouteImport;
      parentRoute: typeof AuthenticatedExpensesRoute;
    };
    '/_authenticated/groups/': {
      id: '/_authenticated/groups/';
      path: '/groups';
      fullPath: '/groups/';
      preLoaderRoute: typeof AuthenticatedGroupsIndexRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    '/_authenticated/groups/$id': {
      id: '/_authenticated/groups/$id';
      path: '/groups/$id';
      fullPath: '/groups/$id';
      preLoaderRoute: typeof AuthenticatedGroupsIdRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    '/_authenticated/students/': {
      id: '/_authenticated/students/';
      path: '/students';
      fullPath: '/students/';
      preLoaderRoute: typeof AuthenticatedStudentsIndexRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    '/_authenticated/students/$id': {
      id: '/_authenticated/students/$id';
      path: '/students/$id';
      fullPath: '/students/$id';
      preLoaderRoute: typeof AuthenticatedStudentsIdRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    '/_authenticated/users/': {
      id: '/_authenticated/users/';
      path: '/users';
      fullPath: '/users/';
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    '/_authenticated/users/$id': {
      id: '/_authenticated/users/$id';
      path: '/users/$id';
      fullPath: '/users/$id';
      preLoaderRoute: typeof AuthenticatedUsersIdRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
  }
}

interface AuthenticatedExpensesRouteChildren {
  AuthenticatedExpensesIdRoute: typeof AuthenticatedExpensesIdRoute;
}

const AuthenticatedExpensesRouteChildren: AuthenticatedExpensesRouteChildren = {
  AuthenticatedExpensesIdRoute: AuthenticatedExpensesIdRoute,
};

const AuthenticatedExpensesRouteWithChildren =
  AuthenticatedExpensesRoute._addFileChildren(
    AuthenticatedExpensesRouteChildren,
  );

interface AuthenticatedRouteChildren {
  AuthenticatedAttendanceRoute: typeof AuthenticatedAttendanceRoute;
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute;
  AuthenticatedExpensesRoute: typeof AuthenticatedExpensesRouteWithChildren;
  AuthenticatedOperatorsRoute: typeof AuthenticatedOperatorsRoute;
  AuthenticatedPaymentsRoute: typeof AuthenticatedPaymentsRoute;
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute;
  AuthenticatedScheduleRoute: typeof AuthenticatedScheduleRoute;
  AuthenticatedTeachersRoute: typeof AuthenticatedTeachersRoute;
  AuthenticatedAuditIdRoute: typeof AuthenticatedAuditIdRoute;
  AuthenticatedBranchesIdRoute: typeof AuthenticatedBranchesIdRoute;
  AuthenticatedCoursesIdRoute: typeof AuthenticatedCoursesIdRoute;
  AuthenticatedGroupsIdRoute: typeof AuthenticatedGroupsIdRoute;
  AuthenticatedStudentsIdRoute: typeof AuthenticatedStudentsIdRoute;
  AuthenticatedUsersIdRoute: typeof AuthenticatedUsersIdRoute;
  AuthenticatedAuditIndexRoute: typeof AuthenticatedAuditIndexRoute;
  AuthenticatedBranchesIndexRoute: typeof AuthenticatedBranchesIndexRoute;
  AuthenticatedCoursesIndexRoute: typeof AuthenticatedCoursesIndexRoute;
  AuthenticatedGroupsIndexRoute: typeof AuthenticatedGroupsIndexRoute;
  AuthenticatedStudentsIndexRoute: typeof AuthenticatedStudentsIndexRoute;
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute;
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAttendanceRoute: AuthenticatedAttendanceRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedExpensesRoute: AuthenticatedExpensesRouteWithChildren,
  AuthenticatedOperatorsRoute: AuthenticatedOperatorsRoute,
  AuthenticatedPaymentsRoute: AuthenticatedPaymentsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedScheduleRoute: AuthenticatedScheduleRoute,
  AuthenticatedTeachersRoute: AuthenticatedTeachersRoute,
  AuthenticatedAuditIdRoute: AuthenticatedAuditIdRoute,
  AuthenticatedBranchesIdRoute: AuthenticatedBranchesIdRoute,
  AuthenticatedCoursesIdRoute: AuthenticatedCoursesIdRoute,
  AuthenticatedGroupsIdRoute: AuthenticatedGroupsIdRoute,
  AuthenticatedStudentsIdRoute: AuthenticatedStudentsIdRoute,
  AuthenticatedUsersIdRoute: AuthenticatedUsersIdRoute,
  AuthenticatedAuditIndexRoute: AuthenticatedAuditIndexRoute,
  AuthenticatedBranchesIndexRoute: AuthenticatedBranchesIndexRoute,
  AuthenticatedCoursesIndexRoute: AuthenticatedCoursesIndexRoute,
  AuthenticatedGroupsIndexRoute: AuthenticatedGroupsIndexRoute,
  AuthenticatedStudentsIndexRoute: AuthenticatedStudentsIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
};

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
